import React, { useState } from 'react';
import { Lead } from '../../types/rivet';
import { ApiService } from '../../services/api';
import { Button } from '../ui/Button';

interface NewInquiryModalProps {
  isOpen: boolean;
  onClose: () => void;
  onAddLead: (newLead: Lead) => void;
}

export const NewInquiryModal: React.FC<NewInquiryModalProps> = ({
  isOpen,
  onClose,
  onAddLead,
}) => {
  const [pasteText, setPasteText] = useState('');
  const [name, setName] = useState('');
  const [phone, setPhone] = useState('');
  const [serviceTitle, setServiceTitle] = useState('Outstation Cab Rental');
  const [travelDate, setTravelDate] = useState('');
  const [pickupLocation, setPickupLocation] = useState('');
  const [notes, setNotes] = useState('');
  const [source, setSource] = useState<'WhatsApp' | 'Website'>('WhatsApp');

  if (!isOpen) return null;

  // Intelligent parser for WhatsApp messages generated by Janai website
  const handleParseWhatsApp = () => {
    if (!pasteText.trim()) return;

    let parsedName = name;
    let parsedPhone = phone;
    let parsedService = serviceTitle;
    let parsedDate = travelDate;
    let parsedPickup = pickupLocation;
    let parsedNotes = notes;

    const lines = pasteText.split('\n');
    lines.forEach((line) => {
      const lower = line.toLowerCase();
      if (lower.startsWith('name:')) {
        parsedName = line.substring(5).trim();
      } else if (lower.startsWith('phone:') || lower.startsWith('mobile:')) {
        parsedPhone = line.substring(line.indexOf(':') + 1).trim();
      } else if (lower.startsWith('service needed:') || lower.startsWith('service:')) {
        parsedService = line.substring(line.indexOf(':') + 1).trim();
      } else if (lower.startsWith('travel date:') || lower.startsWith('date:')) {
        parsedDate = line.substring(line.indexOf(':') + 1).trim();
      } else if (lower.startsWith('pickup location:') || lower.startsWith('pickup:')) {
        parsedPickup = line.substring(line.indexOf(':') + 1).trim();
      } else if (lower.startsWith('notes:')) {
        parsedNotes = line.substring(6).trim();
      }
    });

    setName(parsedName);
    setPhone(parsedPhone);
    if (parsedService) setServiceTitle(parsedService);
    if (parsedDate) setTravelDate(parsedDate);
    if (parsedPickup) setPickupLocation(parsedPickup);
    if (parsedNotes) setNotes(parsedNotes);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim() || !phone.trim()) return;

    const newLead: Lead = {
      id: `ld-${Date.now()}`,
      customerName: name.trim(),
      customerPhone: phone.trim(),
      customerEmail: `${name.toLowerCase().replace(/\s+/g, '.')}@inquiry.com`,
      serviceTitle: serviceTitle.trim(),
      source: source,
      stage: 'New',
      budget: 'To Quote',
      quoteAmount: 'To Quote',
      quoteStatus: 'Not Sent',
      nextFollowUp: 'Today, 6:00 PM',
      assignee: 'Janai Desk',
      createdAt: new Date().toISOString().split('T')[0],
      primaryActionLabel: 'Mark Contacted',
      notes: [
        {
          id: `n-${Date.now()}`,
          author: 'System',
          timestamp: 'Just now',
          text: `Inquiry captured from ${source}. Pickup: ${pickupLocation || 'Central Terminal'}. Travel Date: ${travelDate || 'Flexible'}. ${notes ? `Notes: ${notes}` : ''}`,
        },
      ],
    };

    // Auto-generate a Quote Follow-up task in Supabase
    ApiService.createTask({
      title: `Send quote for ${newLead.serviceTitle}`,
      type: 'Quote Follow-up',
      priority: 'High',
      dueDateTime: newLead.nextFollowUp || 'Today, 6:00 PM',
      assignee: newLead.assignee || 'Janai Desk',
      linkedEntityType: 'Lead',
      linkedEntityName: `${newLead.customerName} (${newLead.serviceTitle})`,
      notes: `Auto-generated from ${source} Intake Bridge. Contact: ${newLead.customerPhone}`,
    }).catch(console.error);

    // Parent will call ApiService.createLead
    onAddLead(newLead);
    onClose();
    setName('');
    setPhone('');
    setTravelDate('');
    setPickupLocation('');
    setNotes('');
    setPasteText('');
  };

  return (
    <div className="rv-lead-drawer-overlay" onClick={onClose}>
      <div
        className="rv-lead-drawer"
        style={{ width: '480px' }}
        onClick={(e) => e.stopPropagation()}
        role="dialog"
        aria-label="New Lead Inquiry Intake Helper"
      >
        {/* Header */}
        <div className="rv-lead-drawer__header">
          <div>
            <h3 style={{ margin: 0, fontSize: '16px', fontWeight: 600, color: 'var(--rv-text-primary)' }}>
              ⚡ New Janai Inquiry Intake
            </h3>
            <span style={{ fontSize: '11px', color: 'var(--rv-text-muted)' }}>
              Convert WhatsApp messages or website inquiries into structured leads
            </span>
          </div>
          <Button variant="ghost" size="sm" onClick={onClose} aria-label="Close modal">
            ✕
          </Button>
        </div>

        {/* Body */}
        <div className="rv-lead-drawer__body">
          {/* Smart WhatsApp Paste Box */}
          <div className="rv-lead-drawer__section" style={{ background: 'var(--rv-bg-base)', padding: '12px', borderRadius: '6px', border: '1px solid var(--rv-border-default)' }}>
            <span className="rv-lead-drawer__label" style={{ marginBottom: '4px' }}>Smart WhatsApp Message Parser</span>
            <textarea
              className="rv-lead-note-input"
              rows={3}
              placeholder="Paste raw WhatsApp inquiry text here (e.g. Name: Rajesh, Phone: +91 98230...)"
              value={pasteText}
              onChange={(e) => setPasteText(e.target.value)}
              style={{ width: '100%', resize: 'vertical' }}
            />
            <Button
              variant="secondary"
              size="sm"
              onClick={handleParseWhatsApp}
              style={{ marginTop: '6px', width: '100%' }}
            >
              ⚡ Auto-Parse Message Fields
            </Button>
          </div>

          {/* Intake Form */}
          <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
              <div>
                <label className="rv-lead-drawer__label" style={{ marginBottom: '4px' }}>Customer Name *</label>
                <input
                  type="text"
                  className="rv-lead-note-input"
                  placeholder="e.g. Rajesh Sharma"
                  required
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  style={{ width: '100%' }}
                />
              </div>

              <div>
                <label className="rv-lead-drawer__label" style={{ marginBottom: '4px' }}>Mobile / WhatsApp *</label>
                <input
                  type="tel"
                  className="rv-lead-note-input"
                  placeholder="+91 98230 11452"
                  required
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                  style={{ width: '100%' }}
                />
              </div>
            </div>

            <div>
              <label className="rv-lead-drawer__label" style={{ marginBottom: '4px' }}>Service Request Title</label>
              <input
                type="text"
                className="rv-lead-note-input"
                placeholder="e.g. Outstation Cab Rental / Manali Package / Airport Transfer"
                value={serviceTitle}
                onChange={(e) => setServiceTitle(e.target.value)}
                style={{ width: '100%' }}
              />
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
              <div>
                <label className="rv-lead-drawer__label" style={{ marginBottom: '4px' }}>Travel Date</label>
                <input
                  type="text"
                  className="rv-lead-note-input"
                  placeholder="e.g. 2026-07-28 / Flexible"
                  value={travelDate}
                  onChange={(e) => setTravelDate(e.target.value)}
                  style={{ width: '100%' }}
                />
              </div>

              <div>
                <label className="rv-lead-drawer__label" style={{ marginBottom: '4px' }}>Pickup Location</label>
                <input
                  type="text"
                  className="rv-lead-note-input"
                  placeholder="e.g. Airport Terminal / City Center"
                  value={pickupLocation}
                  onChange={(e) => setPickupLocation(e.target.value)}
                  style={{ width: '100%' }}
                />
              </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
              <div>
                <label className="rv-lead-drawer__label" style={{ marginBottom: '4px' }}>Inquiry Source</label>
                <select
                  className="rv-lead-note-input"
                  value={source}
                  onChange={(e) => setSource(e.target.value as 'WhatsApp' | 'Website')}
                  style={{ width: '100%' }}
                >
                  <option value="WhatsApp">WhatsApp</option>
                  <option value="Website">Website Form</option>
                </select>
              </div>
            </div>

            <div>
              <label className="rv-lead-drawer__label" style={{ marginBottom: '4px' }}>Internal Notes & Context</label>
              <textarea
                className="rv-lead-note-input"
                rows={2}
                placeholder="Special requirements, flight number, seat preferences..."
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                style={{ width: '100%', resize: 'vertical' }}
              />
            </div>

            <div style={{ fontSize: '11px', color: 'var(--rv-status-callback-text)', background: 'var(--rv-status-callback-bg)', padding: '6px 10px', borderRadius: '4px', border: '1px solid var(--rv-status-callback-border)', marginTop: '8px' }}>
              ⚡ Submitting automatically spawns a "Quote Follow-up" task in the Tasks & Reminders queue for Janai Desk.
            </div>

            <Button type="submit" variant="primary" size="md" style={{ marginTop: '8px' }}>
              + Create Lead & Open Pipeline
            </Button>
          </form>
        </div>
      </div>
    </div>
  );
};
